### ISSUE TITLE
ENH: read_file (GDAL based)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/dask-geopandas#11]
Not all, but many of the spatial file formats supported by GDAL/fiona allow to efficiently read chunks of the file (eg Shapefile, GeoPackage). 

We could have a `dask_geopandas.read_file` variant of `geopandas.read_file` that constructs a partitioned dataframe from such files. 

A small prototype:

```python
import geopandas
import dask_geopandas
from dask.delayed import delayed
import fiona

def read_file(path, npartitions):
    
    with fiona.open(path) as collection:
        total_size = collection.session.get_length()
    
    # TODO smart inference for a good default partition size
    batch_size = (total_size // npartitions) + 1
    
    row_offset = 0
    dfs = []
    
    while row_offset < total_size:
        rows = slice(row_offset, min(row_offset + batch_size, total_size))
        df = delayed(geopandas.read_file)(path, rows=rows)
        dfs.append(df)
        row_offset += batch_size
    
    # TODO this could be inferred from fiona's collection.meta["schema"]
    meta = geopandas.read_file(path, rows=5)
    
    return dd.from_delayed(dfs, meta)
```

And a small experiment with it: https://nbviewer.jupyter.org/gist/jorisvandenbossche/c94bfc9626e622fda7285ed88a4d771a

Since reading those files (currently) doesn't release the gil much, this is mostly useful in a multi-processing setting (and not the default threading scheduler).

I think a function like the above would already be interesting anyway, but for further optimization, using `pyogrio` might be an interesting path: https://github.com/brendan-ward/pyogrio/issues/1

**Comment by maximyudayev** [comment]
@jorisvandenbossche That is a nice solution and one I thought about for my current problem and it is nice to see you went through to deliver a prototype.

But in this case the Dask acyclic graph that gets constructed with ```delayed()``` would depend on each .shp row yielded by fiona since it infers the length of each variable length entry by parsing each row in a singly-linked list fashion ref: [SRI Shapefile Technical Documentation](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf) and fiona does not seem to have the functionality to offset into the file in an array fashion despite existence of complementary .shx file for each .shp.

I am writing a C wrapped Python lib to use .shx file that stores .shp entry offsets in an array fashion using fixed length entries with each row corresponding to the .shp row, such that retrieval of .shp entries will be in constant time and easily parallelizeable across multiple processes.

However, I have not yet come up with a proper way to decide in how many chuncks or what blocksize to use to split each file. Any suggestions? I haven't checked, but maybe Dask read_csv() would be a great example to copy the logic of reading in data from?
