### ISSUE TITLE
BUG: preserve spatial_partitions in GeoDataFrame.set_crs

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/dask-geopandas#58]
Currently, using `set_crs` doesn't preserve the spatial partitions (similar as `copy`, see https://github.com/geopandas/dask-geopandas/pull/56):

```python
import geopandas
import dask_geopandas

gdf = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))
# remove the crs for purpose of the reproducible example
gdf.crs = None

# create partitioned dataframe + calculate spatial partitions
ddf = dask_geopandas.from_geopandas(gdf, npartitions=4)
ddf.calculate_spatial_partitions()

>>> ddf.spatial_partitions
0    POLYGON ((-68.149 -55.612, -68.640 -55.580, -6...
1    POLYGON ((18.465 -29.045, 16.345 -28.577, -77....
2    POLYGON ((166.740 -22.400, -8.899 36.869, -9.5...
3    POLYGON ((-180.000 -90.000, -180.000 -84.713, ...
dtype: geometry
>>> ddf = ddf.set_crs("EPSG:4326")
>>> ddf.spatial_partitions is None
True
```

**Comment by DahnJ** [comment]
The problem is already in `map_partitions`, which returns a new dask object, which I think gets instantiated [here](https://github.com/dask/dask/blob/123cd5f8071daa833cf336dbbef1b16cfcc00554/dask/dataframe/core.py#L6736). As you mentioned in https://github.com/geopandas/dask-geopandas/issues/55#issuecomment-860056926, it might make sense to somehow work out a way in which `spatial_partitions` are somehow attached to the dataframe in a way which Dask respects.

I wrote a short-term solution into https://github.com/DahnJ/dask-geopandas/commit/fabdc2bb12b17ee5fe810582140460181132d17e where I will also then provide a solution to #57

**Comment by jorisvandenbossche** [comment]
> I wrote a short-term solution for set_crs into DahnJ@fabdc2b where I will also then provide a solution to #57.

It's the easiest if you create separate PRs for those.

**Comment by DahnJ** [comment]
> > I wrote a short-term solution for set_crs into [DahnJ/dask-geopandas@fabdc2b](https://github.com/DahnJ/dask-geopandas/commit/fabdc2b) where I will also then provide a solution to #57.
> 
> It's the easiest if you create separate PRs for those.

Good point --> https://github.com/geopandas/dask-geopandas/pull/64
