### ISSUE TITLE
ENH: Implement `spatial_shuffle`

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#88]
We should have a top-level method on `dask_geopandas.GeoDataFrame` and `dask_geopandas.GeoSeries` allowing to shuffle data into spatially coherent partitions. (xref #8)

Let's assume we have `hilbert_distance` and `geohash` functions based on which we can spatially repartition gdf. I would then like to have a single method (`spatial_shuffle`?) that can consume both.

```py
# using hilbert
ddf = ddf.spatial_shuffle('hilbert')

# using geohash
ddf = ddf.spatial_shuffle('geohash')
```

This API can be extended by other methods without the necessity to have two methods for each algorithm (esp. since the `repartition_` methods will be largely the same).

_Originally posted by @martinfleis in https://github.com/geopandas/dask-geopandas/issues/71#issuecomment-876260579_

_note: moving to a separate specific issue to keep track of GSoC._

**Comment by jorisvandenbossche** [comment]
Note that this is basically calling dask's `set_index` with the calculated distance:

```python
ddf_shuffled = ddf.set_index(ddf.geometry.hilbert_distance())
```

But, one thing that we probably also want during that process is to calculate the spatial bounds of each partition, so that the resulting `ddf_shuffled.spatial_partitions` is set. 
I am not fully sure if we can do that more efficiently by tightly integrating that into the `set_index` (which could mean copying some of the dask implementation to be able to adapt it), or whether calling a `ddf.calculate_spatial_partitions()` afterwards is as good.

**Comment by martinfleis** [comment]
I don't think we can make it any faster than calling one after the other.

**Comment by jorisvandenbossche** [comment]
One question from the meeting: we could add a keyword to control whether to actually add the calculated distance as the index or to drop it.

**Comment by jorisvandenbossche** [comment]
This might be worth having a separate issue about, but one of the ideas mentioned in a previous meeting is to also have a way to shuffle two dataframes at the same time with a consistent partitioning (or shuffle one dataframe to align with the partitioning of another).
